default:
  members:
    - WehrführerID

Musterstadt Vollalarm:
  groups:
    - Mannschaft Gruppe
  vehicles:
    - FL MS 1/10
    - FL MS 1/31
    - FL MS 1/46

DLK:
  groups:
    - DLK Gruppe
  vehicles:
    - FL MS 1/10
    - FL MS 1/31

Wehrführung:
  vehicles:
    - FL MS 0/10
  members:
    - WehrführerID