# App zur Alarmierung hier angeben
api: "Divera/Alamos/..."

# API-Key/Accessschlüssel
apiKey: asdf1234

# Start/Restart (bei Fehler) Timeout
timeout: 5000

# Serielles Schnittstelle aktivieren/deaktivieren
serialDME: false

# Mailauswertung aktivieren/deaktivieren
mail: true

# Weiterleiten von Alarmen aktivieren/deaktivieren
alarm: false